spring.application.name=concurrent-booking-system

spring.datasource.url=jdbc:postgresql://localhost:5432/booking_db
spring.datasource.username=booking_user
spring.datasource.password=booking_password

spring.jpa.hibernate.ddl-auto=validate
