CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(320) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    start_time TIMESTAMP WITH TIME ZONE NOT NULL,
    status VARCHAR(32) NOT NULL
);

CREATE TABLE seats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL REFERENCES events (id),
    row_number VARCHAR(20) NOT NULL,
    seat_number INTEGER NOT NULL,
    status VARCHAR(16) NOT NULL,
    price NUMERIC(12, 2) NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT chk_seats_status CHECK (status IN ('FREE', 'BOOKED')),
    CONSTRAINT chk_seats_price CHECK (price >= 0),
    CONSTRAINT uq_seats_event_row_number UNIQUE (event_id, row_number, seat_number)
);

CREATE TABLE bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users (id),
    seat_id BIGINT NOT NULL REFERENCES seats (id),
    status VARCHAR(16) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT chk_bookings_status CHECK (status IN ('ACTIVE', 'CANCELLED'))
);

CREATE INDEX idx_bookings_user_id ON bookings (user_id);
CREATE INDEX idx_bookings_seat_id ON bookings (seat_id);
